### PR TITLE
Allow supplying input file options

### PR DESCRIPTION
**Pull request by whitequark**
See the doc comments for rationale.

### CODE REVIEW

**Comment by mceachen** [comment]
I'll review the PR when the tests pass.

**Comment by whitequark** [comment]
You let the tests bitrot, as evidenced by the empty commit above not passing CI. It's not my responsibility to keep your CI up to date, sorry; everything passes locally so I did my due diligence.

**Comment by mceachen** [comment]
Thanks for updating the tests! I'll push a new version soon.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
